### PR TITLE
WIP Modifications to get datastore working for NII

### PR DESCRIPTION
**Pull request by rossjones**

### CODE REVIEW

**Comment by davidread** [comment]
Are these changes just pulling bits from master ckan? If not, then can you add comments at the start of each block, like `# DGU needs this for datastore compatibility` or something.

**Comment by rossjones** [comment]
Yup, will do.

David Read wrote:

**Comment by rossjones** [comment]
I've merged release-v2.2-dgu into this PR, there are apparently still conflicts.  However if I manually test a merge into release-v2.2-dgu it looks fine.  I am confused.

This now contains the datastore/datapusher code from ckan/ckan and so there are some new files and some small modifications to the existing ones.  There shouldn't be anything DGU specific in here.

**Comment by davidread** [comment]
I think your release-v2.2-dgu branch must have been behind by a few commits. I merged again from it and fixed a conflict.

**Pull request merged**
